# Development / integration testing only
services:
  bot:
    image: node:lts-slim@sha256:35d1cb5434a72b64077da62d4e0175d40e7d940735c234a858f1d95e39e21f39
    volumes:
      - './:/srv/bot'
    working_dir: /srv/bot
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:da8177371c4a7aed7fd673196593c2ff104ce908f300e1971493587622f7a297
    ports:
      - '9411:9411'
