# Development / integration testing only
services:
  bot:
    image: node:lts-slim@sha256:752ea8a2f758c34002a0461bd9f1cee4f9a3c36d48494586f60ffce1fc708e0e
    volumes:
      - './:/srv/bot'
    working_dir: /srv/bot
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:bb570eb45c2994eaf32da783cc098b3d51d1095b73ec92919863d73d0a9eaafb
    ports:
      - '9411:9411'
