# Development / integration testing only
services:
  bot:
    image: node:lts-slim@sha256:d6d1b3a6f21a25e43d765816281b4a86e5f1ebf843cfae1b14dd0f1c28257cc7
    volumes:
      - './:/srv/bot'
    working_dir: /srv/bot
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin@sha256:458b8d0b51e4cc3be0ee51c816fcb3d97a316e4a37462efbe2cb5c9d2a262f5b
    ports:
      - '9411:9411'
