name: Prepare K8S deployment
description: Adds necessary kustomizations prior to deployment
inputs:
  image_version:
    required: true
    description: Image version (tag) to use
  secret_environment:
    required: true
    description: Base64-encoded environment used to generate secrets
runs:
  using: composite
  steps:
    - name: Create .env
      shell: bash
      run: echo "$SECRET_ENVIRONMENT" | base64 -d > ./iac/.env
      env:
        SECRET_ENVIRONMENT: ${{ inputs.secret_environment }}

    - name: Create patch-image-version.yaml
      shell: bash
      run: cat iac/patch-image-version.yaml.in | envsubst > iac/patch-image-version.yaml
      env:
        IMAGE_VERSION: ${{ inputs.image_version }}

    - name: Patch kustomization.yaml
      shell: bash
      run: |
        echo -e "\npatchesStrategicMerge:\n  - 'patch-image-version.yaml'" >> iac/kustomization.yaml
branding:
  color: blue
  icon: battery-charging
