apiVersion: v1
kind: ConfigMap
metadata:
  name: myrnews-bot-configmap
  namespace: bots
data:
  CHAT_ID: "-1001454569993"
  KNEX_DRIVER: mysql2
  LISTEN_HOST: "0.0.0.0"
  NEWS_ENDPOINT: https://myrotvorets.news
  NODE_ENV: production
  PATH_PREFIX: psbnews
  WEBHOOK_DOMAIN: tgbots.myrotvorets.center
  WEBHOOK_PORT: "3010"
  OTEL_TRACES_EXPORTER: otlp
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector.default.svc.cluster.local:4317
