name: Build and Test

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches:
      - '**:**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      head_tag: ${{ steps.head_tag.outputs.head_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Retrieve tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Check if Git tag exists
        id: head_tag
        run: echo "::set-output name=head_tag::$(git tag --points-at HEAD)"
        if: startsWith(github.ref, 'refs/heads/')

  build:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ !startsWith(github.ref, 'refs/heads/') || !needs.prepare.outputs.head_tag }}
    strategy:
      matrix:
        node_version:
          - 'lts/*'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: https://npm.pkg.github.com
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run postinstall scripts
        run: npm rebuild && npm run prepare --if-present

      - name: Run tests
        run: npm test

      - name: Trigger Docker build
        uses: myrotvorets/trigger-repository-dispatch-action@1.1.1
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          type: tests-passed
          payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "event_name": "${{ github.event_name }}" }'
