name: Docker Image CI (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.2
    - run: touch production.env
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myrnews-tgbot:$(date +%s)
