name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        default: edge
        required: true
        description: Docker image tag

env:
  IMAGE_NAME: myrotvorets/myrnews-tgbot

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Prepare the files
        uses: myrotvorets/composite-actions/prepare-k8s-deployment@master
        with:
          image_version: ${{ github.event.inputs.tag }}
          secret_environment: ${{ secrets.SECRET_ENVIRONMENT }}
          path: iac

      - name: Start deployment
        uses: chrnorm/deployment-action@d42cde7132fcec920de534fffc3be83794335c00 # v2.0.5
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: production

      - name: Deploy
        uses: myrotvorets/kubectl-action@49846ef8e3f63df58b7def8a792bbc7407859dd4 # tag=2.0.1
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: 1.21
          args: apply -k iac/

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@2afb7d27101260f4a764219439564d954d10b5b0 # tag=v2.0.1
        with:
          token: "${{ github.token }}"
          state: "success"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@2afb7d27101260f4a764219439564d954d10b5b0 # tag=v2.0.1
        with:
          token: "${{ github.token }}"
          state: "failure"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Cleanup
        if: always()
        run: rm -f ./iac/.env
